### ISSUE TITLE
Possible fix for "C scroll stock running out so fast"

### ISSUE THREAD

**Issue by ghost** [dun1007/fateanother#1]
```
Q) Why is C scroll stock running out so fast?

A) In Dota 2 the stock in shop is team-bound, not personal and there's no way to do anything about it at the moment. It is very likely that someone else have hogged all scrolls before you get your hands on them.
```

For this you can have the C scroll have an unlimited stock, and when the player buys a C scroll (In OnItemPurchased), check the player's C-scroll count. If player has too many C scrolls > delete item > reproduce C scroll item with correct charges > display custom error message.

**Comment by dun1007** [comment]
I resolved that issue month ago but forgot to remove it from the FAQ. When you are in base, it checks if you have exceeded the amount of scroll that can be bought for base price : https://github.com/dun1007/fateanother/blob/master/game/dota_addons/fateanother/scripts/vscripts/addon_game_mode.lua#L599. Thanks for reminder though :)
