### ISSUE TITLE
Avenger's Verg crashes server when hit by ally linked by Spirit Link

### ISSUE THREAD

**Issue by gelguy** [dun1007/fateanother#101]
Possible ally damage sources - Lancelot's Nuke, Gawain W ally attack aura

An infinite loop occurs with basically 0 damage being passed around the DamageFilter and DoDamage.

Quick fix would be to set a minimum damage to reflect or be shared by link.

Maybe preventing Verg from damaging allies works as well.

**Comment by dun1007** [comment]
Preventing damage reflect to allies makes sense

**Comment by gelguy** [comment]
I feel like I've seen Lancelot nuking allied Avengers and dying quite a few times. Should this be kept?

**Comment by dun1007** [comment]
It would make sense to keep the TK interaction if the skill is designed to deliberately damage an ally
