### ISSUE TITLE
Possible fix for "I get 'Cannot Take Items' error when trying to buy item!"

### ISSUE THREAD

**Issue by ghost** [dun1007/fateanother#2]
```
Q) I get 'Cannot Take Items' error when trying to buy item! 

A) Select your hero and try again. A unit cannot carry an item.
```

There's a couple KVs that allow units to carry items. "HasInventory" and "ConsideredHero". [See this](https://github.com/MNoya/DotaCraft/blob/cb68afb15b8064fd7616db1672d2e65add017255/scripts/npc/units/human_buildings.txt#L38-L39)

**Comment by dun1007** [comment]
I was aware of HasInventory but did not know about ConsideredHero. Works like a charm, thanks!
