### ISSUE TITLE
White Saber Galatine over-heals by target's current health

### ISSUE THREAD

**Issue by gelguy** [dun1007/fateanother#32]
https://github.com/dun1007/fateanother/blob/2dd8e965c72126db60474dc9a652793f086226e4/game/dota_addons/fateanother/scripts/vscripts/gawain_ability.lua#L194

``` lua
v:Heal(v:GetHealth() + keys.Damage * 33/100, caster)
```

`v:GetHealth()` should be removed.

**Comment by dun1007** [comment]
5e9c59ab44a2326b67a587a66e9edf98658b6016

**Comment by gelguy** [comment]
https://github.com/dun1007/fateanother/blob/5e9c59ab44a2326b67a587a66e9edf98658b6016/game/dota_addons/fateanother/scripts/vscripts/gawain_ability.lua#L199

Sunlight Galatine still overheals.
