### ISSUE TITLE
Teleport into marbles

### ISSUE THREAD

**Issue by gelguy** [dun1007/fateanother#37]
Put a ward the top edge of UBW using a scout familiar and you can teleport to it.

You cannot target teleport below the -2000 coordinate, but if you target just above that (which is just below the pathable part of the map), it is within the 2000 range acquisition of the ward. This lets you teleport into UBW.

**Comment by dun1007** [comment]
bf44cdbd721138cddec80eddfd6f4f0452cfbd75
