### ISSUE TITLE
Lancer 5 targeted Gae Bolg doing damage off current health instead of max health

### ISSUE THREAD

**Issue by gelguy** [dun1007/fateanother#38]
https://github.com/dun1007/fateanother/blob/2dd8e965c72126db60474dc9a652793f086226e4/game/dota_addons/fateanother/scripts/vscripts/lancer_ability.lua#L247

``` lua
keys.Damage = keys.Damage + target:GetHealth()*healthDamagePct/100
```

**Comment by dun1007** [comment]
It is working as intended since Lancer's Rune of Flame adds bonus damage based on current health

**Comment by gelguy** [comment]
My bad, linked the wrong line.

https://github.com/dun1007/fateanother/blob/2dd8e965c72126db60474dc9a652793f086226e4/game/dota_addons/fateanother/scripts/vscripts/lancer_ability.lua#L260-L268

Line 264 specifically.

The Improved Gae Bolg tooltip indicates it does 10% of target's max health over 3 seconds.
