### ISSUE TITLE
Heroes with Spirit Link buff cannot take lethal damage

### ISSUE THREAD

**Issue by gelguy** [dun1007/fateanother#40]
Even the main target will not take lethal damage, e.g. if you have 500 hp, linked with 1 other person, and take 1200 damage, you will be reduced to 1 hp even though it would have been lethal on the main target. This makes it pretty much a Battle Continuation.

Is this intended?

If no, one solution would be to apply non-lethal damage flag when doing ApplyDamage if isLoop is true, and removing the Spirit Link buff if health is 1. This means the main target can still take lethal damage, but the linked targets will not, and the spirit link buff removed.

**Comment by dun1007** [comment]
Spirit Link always leaves victim with 1 hp no matter how much damage is shared. One of reasons why it is such a strong item in high level games.
