### ISSUE TITLE
-bgmoff not working

### ISSUE THREAD

**Issue by gelguy** [dun1007/fateanother#41]
https://github.com/dun1007/fateanother/blob/da030c29ec794ce80cde9349490bc52422dd109a/content/dota_addons/fateanother/panorama/scripts/custom_game/fateanother_bgm.js#L53

I think it should follow the EmitSound format where the sound name is passed to it instead of the entindex.

``` lua
var BGMname = "BGM." + g_GameConfig.curBGMIndex.toString();
g_GameConfig.curBGMentindex = Game.StopSound(BGMname);
```

This also affects the changing of BGM using the dropdown menu. The previous song is not stopped.

**Comment by dun1007** [comment]
This is a tricky problem because StopSound function in Javascript API requires an index of soundevent emitted by EmitSound. I cannot pass sound name to stop it.

Back in the days BGM was handled on lua script via EmitSoundOnClient but it is broken now

**Comment by gelguy** [comment]
Good point - I just looked at the API and it does indeed take the integer handle.

I take it that StopSound is just bugged and not working at the moment?

**Comment by gelguy** [comment]
Quark has pointed out that you can `-bgmoff` if u type `-bgmon` first.

Update: the BGM turns back on after a while.

**Comment by sngweicong** [comment]
Currently,
-bgmoff works when you do it after it cycles to next song, which is approximately a few seconds before end of round 1.

For g_GameConfig.curBGMentindex, events as follows;

Hit team select screen, team_select.js line 4, value gets initialized to 0.
PlayBGM called once at team_select.js line 430, value now not 0.
Choose any hero, click "Enter battle", fateanother_customization.js line 3, value gets reinitialized to 0.
Types -bgmoff, value is 0, so StopBGM doesn't call StopSound.
The next time value gets changed away from 0 would be when current BGM ends and PlayBGM gets called again, only then StopBGM will call StopSound

Blocking reinitialization at 
https://github.com/dun1007/fateanother/blob/765a5d906512323db3d507a0988270b7c0ce7890/content/dota_addons/fateanother/panorama/scripts/custom_game/fateanother_customization.js#L3
appears to solve the problem.
