### ISSUE TITLE
C scroll not killing scout familiar

### ISSUE THREAD

**Issue by gelguy** [dun1007/fateanother#47]
https://github.com/dun1007/fateanother/blob/master/game/dota_addons/fateanother/scripts/vscripts/libraries/util.lua#L1027

Due to the rounding, at certain INT values C scroll will only do 199 damage instead of the intended 200. This makes C scrolls leaving scout familiars at 1 hp sometimes.

This might be due to the engine rounding down for damage values? Not entirely sure.

The 1 damage difference can also affect other spells which use threshold values. One that comes to mind is S scroll against Saber's Avalon doing 299 instead of 300 (after magic resist).

**Comment by dun1007** [comment]
https://github.com/dun1007/fateanother/blob/master/game/dota_addons/fateanother/scripts/vscripts/libraries/util.lua#L1026-L1028

I believe this is happening due to roundoff error from the formula used to offset spell damage amplification from INT

**Comment by gelguy** [comment]
The INT values I have found to do 1 less damage than expected are `13`, `15`, `22`, `30`, `39`, `40`, `46` and `47` (up to 50).

Not sure of the significance of these numbers at the moment.

**Comment by dun1007** [comment]
a604df7

**Comment by dun1007** [comment]
5e9c59ab44a2326b67a587a66e9edf98658b6016
