### ISSUE TITLE
Anti-camp system abuse

### ISSUE THREAD

**Issue by xRainZx** [dun1007/fateanother#48]
Currently there is a flaw on losing team taking advantage of anti -camp system with tp scroll. 

The losing team would plant some wards on mid.  And send a familair ward across the map and plant a ward.

When the winning team rushes in and near the loaing team,  the whole losing team would use tp scroll to teleport to the opposite of the map.

If its before its acceptable as a strat.  But current mode of 2 minute is too short and the winning team had to run back after crossing the bridge,  and cost alot of time to do so.  It quickly became unhealthy. 

Infact this kind if play is happening alot of times recently.

It happens mostly in a game where a team snowballs real hard and the losing team decide to max camp + tp ward strat just to firce draw for win. 

A few suggestions would be
A)  increase tp cast time each time a new tp scroll comes in on the same ward. 
B)  increase cast time long as the further the targeted ward between the user is. 
C)  setting  tp  scroll  range  limit

**Comment by dun1007** [comment]
Please refrain from opening issue for balance related matter.

**Comment by xRainZx** [comment]
my bad, was in a bad mood before I posted this and didn't think of the consequences.
