### ISSUE TITLE
Tsbuame Gaeshi not applying on-hit effect when Ganryu is acquired

### ISSUE THREAD

**Issue by gelguy** [dun1007/fateanother#49]
https://github.com/dun1007/fateanother/blob/fe97041ec900e0e4097be63ec6cd8932e042e129/game/dota_addons/fateanother/scripts/vscripts/fa_ability.lua#L574-L585

https://github.com/dun1007/fateanother/blob/fe97041ec900e0e4097be63ec6cd8932e042e129/game/dota_addons/fateanother/scripts/vscripts/fa_ability.lua#L605-L616

https://github.com/dun1007/fateanother/blob/fe97041ec900e0e4097be63ec6cd8932e042e129/game/dota_addons/fateanother/scripts/vscripts/fa_ability.lua#L636-L647

Last hit does not apply stun effect as well.

**Comment by dun1007** [comment]
630a2d958266accda23a36dd36521658b8f735a9
