### ISSUE TITLE
Lancelot E-R spellbook cooldown interaction with Gawain Sunlight W

### ISSUE THREAD

**Issue by gelguy** [dun1007/fateanother#55]
Now that Lancelot's Arondite puts all Knight of Honor spells on cooldown, it is still possible to have Gawain  Sunlight W hit Lancelot and reduce all the cooldowns to zero.

**Comment by sngweicong** [comment]
Hello, just want to check, the only way for this to happen is when gawain issues attack command on lancelot first, before lancelot activates KoH-arondite?

**Comment by gelguy** [comment]
Yep, otherwise Gawain is unable to target Lancelot for the attack.

**Comment by gelguy** [comment]
Fixed by 17701e0.
