### ISSUE TITLE
Vector(0,0,0) Issue with Particle and Sound

### ISSUE THREAD

**Issue by dun1007** [dun1007/fateanother#6]
Recent patch brought forth an [issue with sound](http://dev.dota2.com/showthread.php?t=187167). Possible workarounds are making an alternative function in utils.lua or listening to sound event from Panorama, proposed by [Karawasa](https://github.com/Karawasa).

Also few particles play its child on Vector(0,0,0), such as Archer(5th)'s Hrunting and occassionally Caster(5th)'s Argos. This is an independent issue caused by mismatching/null control point setup, most likely.

**Comment by MNoya** [comment]
Proposed by BMD really :smile: 

This commit shows what you need to add: https://github.com/MNoya/DotaCraft/commit/9c586aaf2d5a110948581201b8d5f89be15ccf99

**Comment by dun1007** [comment]
I would believe it if someone said BMD senpai created humans from dust on sixth day

**Comment by dun1007** [comment]
Tried [this](https://github.com/dun1007/fateanother/commit/99a310e5e3ed9df88dd665527c01154fad330cf7) but the sound still doesn't play. The console displays sound name from panorama correctly though. Any idea?

**Comment by dun1007** [comment]
Sound issue was resolved by 92aa7681b44fd776552502f40258f09153bb40ab
