### ISSUE TITLE
Use CastFilter

### ISSUE THREAD

**Issue by gelguy** [dun1007/fateanother#75]
Currently, most of the spell conditions are checked after the spell is cast. If the conditions are not met (e.g. blink onto unpathable terrain), the spell mana is refunded and the cooldown ended.

However, this means that the unit would have already casted the spell - unit would have turned to face direction, unit would have spent time for the ability's cast point, etc. This also will remove the targeting cursor, and so if you perform a failed blink, you have to press the hotkey to blink again.

Using the CastFilter will allow the conditions to be checked before the spell is cast, and be a better indicator of whether the spell was successfully cast or not.

Spells which would benefit from this include

- Blink scroll
- Caster 5 R
- Caster 5 Mana Transfer (cannot target self)
- Caster 5 Workshop Recall (can only target Caster 5)
- Avenger's Dark Passage
- Tamamo's Mantra (cannot cast on target which already has Mantra)

**Comment by gelguy** [comment]
After fiddling around with CastFilter I've come to the conclusion it is currently not worth the effort to implement it. This is due to 2 major issues.

The first issue is that not all information is available to the client. From what I've gathered, the CastFilter has two phases, one on the client side and one on the server side. The client side handles the casting and targeting UI, mostly whether the cursor becomes disabled. If the client initiates the casting of the spell, the server side then checks once again if the conditions of the filter are met. Only after the server side check passes does the hero turn (and move if he is out of range) to cast the spell. 

However, [not all information is available on the client side](http://dev.dota2.com/showthread.php?t=178863). One of the key missing bit of information is the GridNav. Without the GridNav, Blink scroll and location targeted spells will only be checked on server side. This might include modifier checks as well.

This means my assumption that the targeting cursor remains after a failed check becomes wrong. What is correct would be that the hero will not turn and attempt to cast the spell if the check fails (which matters for spells with more than 0 cast point e.g. Dark Passage).

The second issue would be that CastFilter is only available to `ability_lua` or `item_lua`. Currently, most, if not all the spells use `_datadriven`. To convert them, the functions mostly remain the same other changes to `key` variables. However, the structure of the repo needs to be adjusted so that each spell is handled in its own individual file (see [Crumbling Island Arena](https://github.com/DoctorGester/crumbling-island-arena) for a good example of entirely lua driven). I do believe that we should make the repo more structured but perhaps now is not the best time with new heroes and patches coming soon.

I am closing this issue for now, but might reopen later in the future. The not turning and moving to cast the spell is indeed a good QoL improvement and will make it more inline with the casting interface of Dota 2.

**Comment by dun1007** [comment]
It would be feasible to recode subject abilities as lua ability down the road, but indeed it is not a top priority task.
