### ISSUE TITLE
Lancer 4's Mind's Eye increases vision range by 250

### ISSUE THREAD

**Issue by gelguy** [dun1007/fateanother#81]
https://github.com/dun1007/fateanother/blob/master/game/dota_addons/fateanother/scripts/vscripts/lancer_ability.lua#L19-L24

In addition to giving flying vision of 1000 (which is +150 over normal vision), acquiring the attribute increases Lancer 4's normal vision to 1100 (+250).

Not sure if intended.

**Comment by dun1007** [comment]
WC3 attribute had a hidden property that increased ZL's vision range.
