### ISSUE TITLE
Spell effects vs magic immunity

### ISSUE THREAD

**Issue by gelguy** [dun1007/fateanother#84]
Crossed out indicates effect is intended.

- [x] ~~Rider 5's Bloodfort with Seal silence and forced movement~~
- [x] ~~EA's Martial Arts silence proc~~
- [x] ~~Tamamo's charm procs with autoattack~~
- [x] Tamamo's Shackle drag (Mantra applied before magic immunity is applied, shackle particle is not visible)
- [x] ~~FA's Windblade knockback~~
- [x] ~~Lancer 4's Lovespot silence and forced movement~~
- [x] Saber's Invisible Air if projectile is fired before magic immunity is applied
- [x] ~~Saber's Strike Air Upstream airborne~~
- [x] Black Rider's Vanish if projectile is fired before magic immunity is applied
- [x] ~~Caster 5's Wall of Flame knockback~~
- [x] ~~Berserker 5's Nine Lives last hit knockback (I assume the other Nine Lives are affected as well)~~

**Comment by dun1007** [comment]
Unchecked ones are not intended

**Comment by gelguy** [comment]
Updated.

Also to clarify, since it seems like knockbacks are meant to pierce spell immunity, should Saber's Strike Air or Archer 5's E with attribute? They currently do not.
