### ISSUE TITLE
Pause state on 1st round (pre-round) not working properly.

### ISSUE THREAD

**Issue by xRainZx** [dun1007/fateanother#96]
The pause state on 1st round doesn't seems to work and players are able to move as soon as the pre-round begin to count down instead of the actual round timer starts, giving players who buys item using keybinds / macro a kind of advantage advancing to the middle of the map VS who buys item slowly / click-to-buy kind of players.

(It's not a big advantage and isn't much of a huge issue, but it's funny to see people standing still without doing anything on the 1st round [player who doesn't know about this] while player who knows will rush buys and rush to the opposite of the map.

**Comment by gelguy** [comment]
Caused by https://github.com/dun1007/fateanother/blob/master/game/dota_addons/fateanother/scripts/vscripts/addon_game_mode.lua#L447-L449.

Think this is code left over from refactoring the Blessing timers out of `InitializeRound` into the  `startgame` timer.

Need @dun1007 to confirm if intended.

**Comment by dun1007** [comment]
This is not intended
